---
version: '2.1'

services:

  taiga-db:
    image: postgres:9.6
    expose:
      - "5432"
    networks:
      - taiga-net
    volumes:
      - taiga_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER:-taiga}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-taiga}"
      POSTGRES_DB: "${DB_NAME:-taiga}"

  taiga-back:
    image: gangefors/taiga-back
    build:
      context: taiga-back
    ports:
      - "8000"
    networks:
      - taiga-net
    links:
      - taiga-db:postgres
    volumes:
      - taiga_back_logs:/taiga/logs/
      - taiga_back_media:/taiga/media/
      - taiga_back_static:/taiga/static/
    hostname: "${HOSTNAME:-localhost}"
    environment:
      DEBUG: "${DEBUG}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST:-taiga-db}"
      DB_PORT: "${DB_PORT:-5432}"
      API_SCHEME: "${API_SCHEME}"
      API_DOMAIN: "${API_DOMAIN}"
      FRONT_SCHEME: "${FRONT_SCHEME:-https}"
      FRONT_DOMAIN: "${FRONT_DOMAIN}"
      TIME_ZONE: "${TIME_ZONE}"
      LANGUAGE_CODE: "${LANGUAGE_CODE:-en-us}"
      SECRET_KEY: "${SECRET_KEY}"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
      SERVER_EMAIL: "${SERVER_EMAIL}"
      EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      PUBLIC_REGISTER_ENABLED: "${PUBLIC_REGISTER_ENABLED}"
      FEEDBACK_ENABLED: "${FEEDBACK_ENABLED}"
      FEEDBACK_EMAIL: "${FEEDBACK_EMAIL}"
      STATS_ENABLED: "${STATS_ENABLED}"

  taiga-front:
    image: gangefors/taiga-front
    build:
      context: taiga-front
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    networks:
      - taiga-net
    links:
      - taiga-back:taiga-back
    volumes:
      - taiga_back_logs:/taiga/logs/
      - taiga_back_media:/taiga/media/
      - taiga_back_static:/taiga/static/
    hostname: "${HOSTNAME:-localhost}"
    environment:
      API_URL: "${API_URL:-/api/v1/}"
      DEBUG: "${DEBUG:-false}"
      FEEDBACK_ENABLED: "${FEEDBACK_ENABLED:-false}"
      FRONT_SCHEME: "${FRONT_SCHEME:-https}"
      FRONT_LANGUAGE: "${FRONT_LANGUAGE:-en}"
      PUBLIC_REGISTER_ENABLED: "${PUBLIC_REGISTER_ENABLED:-true}"
      USE_GRAVATAR: "${USE_GRAVATAR:-true}"

volumes:
  taiga_db_data:
    driver: local
  taiga_back_logs:
    driver: local
  taiga_back_media:
    driver: local
  taiga_back_static:
    driver: local

networks:
  taiga-net:
    driver: bridge
