#!/bin/sh

# Configure taiga front
cat > /taiga/front/dist/conf.json <<EOL
{
  "api": "${API_URL:-/api/v1/}",
  "eventsUrl": null,
  "eventsMaxMissedHeartbeats": 5,
  "eventsHeartbeatIntervalTime": 60000,
  "eventsReconnectTryInterval": 10000,
  "debug": ${DEBUG:-false},
  "debugInfo": false,
  "defaultLanguage": "${FRONT_LANGUAGE:-en}",
  "themes": ["taiga"],
  "defaultTheme": "taiga",
  "publicRegisterEnabled": ${PUBLIC_REGISTER_ENABLED:-true},
  "feedbackEnabled": ${FEEDBACK_ENABLED:-true},
  "privacyPolicyUrl": null,
  "termsOfServiceUrl": null,
  "maxUploadFileSize": null,
  "contribPlugins": [],
  "tribeHost": null,
  "gravatar": ${USE_GRAVATAR:-true}
}
EOL

# Get site conf
SITE_CONF=${FRONT_SCHEME:-http}.conf

# Generate self-signed certificates
if [ "$FRONT_SCHEME" = "https" -a ! -f /etc/ssl/client.key ]; then
    openssl req -subj "/C=/ST=/L=/O=/CN=${HOSTNAME:-localhost}" \
        -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/cert.key \
        -out /etc/ssl/cert.crt
fi

# Disable all sites
rm -f /etc/nginx/conf.d/*

# Enable configured site
ln -sf /etc/nginx/${SITE_CONF} /etc/nginx/conf.d/

nginx -g "daemon off;"
